name: Test DAPP API

on:
  push:

jobs:
  build-dotnet:
    name: Test DAPP-API
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.x

    - name: Restore dependencies
      run: cd implementation/DAPP && dotnet restore

    - name: Install ImageMagick
      run: Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1')) && choco install imagemagick -y
    
    - name: Build
      run: cd implementation/DAPP && dotnet build --no-restore
    
    - name: Test
      run: cd implementation/DAPP && dotnet test --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura
    
    - name: Report code coverage
      uses: codecov/codecov-action@v2
      with:
        file: ./implementation/DAPP/coverage.cobertura.xml
